name: Build-and-checks
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Formating:
    name: Automatic formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checking coding style
        run: |
          cp ./scripts/clang-formating.sh ./clang-formating.sh
          ./clang-formating.sh

  Linters:
    name: Running linters check
    runs-on: ubuntu-latest
    needs: Formating
    steps:
      - name: Build library and check with linters
        run: |
          ls -la
          sudo apt install clang-tidy
          cp ./scripts/build.sh ./build.sh
          ./build.sh -l
          cd build
          make clang-tidy-check

  Building:
    name: Build hw solution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building
        run: |
          cp ./scripts/build.sh ./build.sh
          ./build.sh