name: Build-and-checks
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Building:
    name: Build hw solution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building
        run: |
          cp ./scripts/build.sh ./build.sh
          ./build.sh