name: Build-and-checks
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Formating:
    name: Automatic formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Formating files
        run: |
          cp ./scripts/clang-formating.sh ./clang-formating.sh
          ./clang-formating.sh
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: dev
  Linters:
    name: Running linters checks
    runs-on: ubuntu-latest
    needs: Formating
    steps:
      - name: Build library and check with linters
        run: |
          sudo apt install clang-tidy
          cp ./scripts/build.sh ./build.sh
          ./build.sh -l
          cd build
          make clang-tidy-check

  Building:
    name: Build hw solution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Building
        run: |
          cp ./scripts/build.sh ./build.sh
          ./build.sh