name: Build-and-checks
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Formating:
    name: Automatic formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checking coding style
        run: |
          cp ./scripts/clang-formating.sh ./clang-formating.sh
          ./clang-formating.sh

  Linters:
    name: Running linters check
    runs-on: ubuntu-latest
    needs: Formating
    steps:
      - uses: actions/checkout@v2
      - name: Run linters checks
        run: |
          cp ./scripts/build.sh ./build.sh
          ./build.sh
          cp ./scripts/analyzers-check.sh ./analyzers-check.sh
          ./analyzers-check.sh
      - name: Build library and check with clang-tidy
        run: |
          sudo apt install clang-tidy
          cp ./scripts/build.sh ./build.sh
          ./build.sh -lt
          cd build
          make clang-tidy-check