name: Build-and-checks
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Formating:
    name: Automatic formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checking coding style
        run: |
          ./scripts/clang-formating.sh

  Linters:
    name: Running linters check
    runs-on: ubuntu-latest
    needs: Formating
    steps:
      - uses: actions/checkout@v2
      - name: Run linters checks
        run: |
          ./scripts/build.sh -lt
          ./scripts/analyzers-check.sh
      - name: Build library and check with clang-tidy
        run: |
          sudo apt install clang-tidy
          ./scripts/build.sh -l
          cd build
          make linter-check