name: Build-and-checks
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Testing:
    name: Run tests and generate coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing
        run: |
          cp ./scripts/build.sh ./build.sh
          ./build.sh -tc
          cd build
          ctest
          cd ..
      - name: Generate coverage report
        run: |
          cp ./scripts/coverage-generator.sh coverage-generator.sh
          ./coverage-generator.sh
      - name:  Getting code coverage data
        uses: codecov/codecov-action@v2
        with:
          token: 6159713c-1d25-4419-9556-de04e1663b81
          files: coverage.xml
