name: Tests passing
on: [ push ]
defaults:
  run:
    shell: bash
jobs:
  Testing:
    name: Run tests and generate coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Tests
        run: |
          sudo apt update
          sudo apt install valgrind
          export ASAN_OPTIONS=verify_asan_link_order=0
          ./scripts/build.sh -tc
          cd build
          make
          cd ..
      - name: Run Tests SolverTests
        run: |
          valgrind --tool=memcheck ./build/SolverTests
          ./build/SolverTestsAddress
          ./build/SolverTestsThread
          ./build/SolverTestsUndefined
      - name: Run Tests PointTests
        run: |
          valgrind --tool=memcheck ./build/PointTests
          ./build/PointTestsAddress
          ./build/PointTestsThread
          ./build/PointTestsUndefined
      - name: Generate coverage report
        run: |
          ./scripts/coverage-generator.sh
      - name: Getting code coverage data
        uses: codecov/codecov-action@v2
        with:
          token: 6159713c-1d25-4419-9556-de04e1663b81
          files: coverage.xml
